// Generated by CoffeeScript 1.10.0
(function() {
  var WispCompiler, compile;

  compile = require('wisp/compiler').compile;

  module.exports = WispCompiler = (function() {
    WispCompiler.prototype.brunchPlugin = true;

    WispCompiler.prototype.type = 'javascript';

    WispCompiler.prototype.extension = 'wisp';

    function WispCompiler(config) {
      this.config = config;
      return;
    }

    WispCompiler.prototype.compile = function(data, path, callback) {
      var err, error, error1, res, result;
      try {
        res = compile(data, {
          'source-uri': path
        });
        return result = {
          data: res['code']
        };
      } catch (error1) {
        err = error1;
        return error = err;
      } finally {
        callback(error, result);
      }
    };

    return WispCompiler;

  })();

}).call(this);
